### ISSUE TITLE
Add facebook messenger support

### ISSUE THREAD

**Issue by buesing** [nygardk/react-share#100]
Facebook messenger support would be great. It seems to be very easy: https://developers.facebook.com/docs/sharing/messenger/

**Comment by ez2torta** [comment]
+1

**Comment by zpfreed** [comment]
+1

**Comment by KarinaShapran** [comment]
+1

**Comment by milkins87** [comment]
+1

**Comment by aautio** [comment]
Facebook Messenger does not provide an HTTP api that we could use to do this.

I'm closing the issue as there is no solution in sight.
