### ISSUE TITLE
Allow Accessible Rich Internet Applications (ARIA) on generated buttons

### ISSUE THREAD

**Issue by fabrz** [nygardk/react-share#101]
Would be nice to be able to use `aria` attributes for accessibility.

**Comment by nygardk** [comment]
You can now set `additionalProps` object to share buttons. It should solve this issue!

**Comment by mahowa** [comment]
Might be nice to include this info in the ReadMe @nygardk

**Comment by mahowa** [comment]
Also it would be nice if I could override the role property if I wanted it to be something other than button
