### ISSUE TITLE
280 character tweet support

### ISSUE THREAD

**Issue by GeeWizWow** [nygardk/react-share#102]
Hi 

Will we need to update the lib for access to 280 character tweets or will it happen on twitter's side?
As a side note do you know when that might be?

Thanks

**Comment by aautio** [comment]
Twitter has increased the tweet character limit to 280 characters. It has already happened. You do not need to update this library, but you might need to update the native Twitter apps in your phones.

Including the url in a tweet takes a few characters. 23 if I remember correctly. Thus you have about 257 characters which you can use to describe the link.
