### ISSUE TITLE
Share count not showing when used with Next.js SSR

### ISSUE THREAD

**Issue by jaanhio** [nygardk/react-share#105]
Hi, i am using react-share (in particular the Facebook share API) with my blog built using React + Next.js (SSR) + CosmicJS (CMS).

For some reason, the share count isn't displaying. I tried to share the link via the demo and it works so im thinking the bug probably lies with Next.js.

i checked using Chrome React Dev Tool and can see that <SocialMediaShareCount /> isnt showing any state. Any idea how i can work around it?

**Comment by nygardk** [comment]
Sorry for a late, delayed answer to this. SSR usually don't handle asynchronous calls very well. The underlaying problem is probably that the server doesn't know when the share count actually returns, and most likely returns the rendered string before it gets the actual count, so it'll be never displayed. There's no easy solution to this, AFAIK.

**Comment by Itagiba** [comment]
@jaanhio how are you implementing this with next.js with `.window` and `document.`?

**Comment by aautio** [comment]
I'm closing the issue as an old one. Please reopen if the issue requires further discussions.
