### ISSUE TITLE
counter is not updated when the prop url is changed

### ISSUE THREAD

**Issue by efernandesng** [nygardk/react-share#11]
Hi,

The counter is only updated on `componentDidMount` (Invoked once, only on the client). When we change prop `url`, the counter is not updated.

Maybe, we need update counter on `componentWillReceiveProps` or `componentWillUpdate`.

Thanks

**Comment by nygardk** [comment]
Hi,

Thanks for the comment. I will look into this when I've got time!

**Comment by BigNom** [comment]
Hi mate

I got this message when I installed the dependencies, after I installed the file-loader it worked a treat.
 
npm WARN url-loader@0.5.7 requires a peer of file-loader@* but none was installed.

Cheers

**Comment by nygardk** [comment]
#11 is fixed in version 1.8.0.
