### ISSUE TITLE
Is it possible to dynamically change the message in the FB Share pop up?

### ISSUE THREAD

**Issue by SandMoshi** [nygardk/react-share#110]
I want for users to be able to share their score after the end of each game they play.

Is there a way for me to dynamically pre-fill the share box with a short message that includes their score?

I noticed the `description={} ` is deprecated. Is there any other option?

**Comment by SandMoshi** [comment]
I noticed that the new `quote={}` prop is able to do this. 

I was originally using the npm README and didn't notice the github README was updated. Is there  a reason the npm is so outdated it still lists `description={}` and `title={}` as valid props for fbshare?

**Comment by SandMoshi** [comment]
I guess a follow up question is why does it have to be a quote? Can't it be normal text or did FB disallow that?

**Comment by nygardk** [comment]
I think the difference between old "description" and new "quote" is just semantics. They work the same, don't they?

**Comment by SandMoshi** [comment]
I don't think so. The quote shows up as a smaller font with a background behind the text. It looks different than what a shared post's text would appear.

**Comment by nygardk** [comment]
Ok! The `description` and `title` were deprecated due to Facebook API change, but then again, I'm not certain if the API is really actually deprecated (or disabled). If you can find info about this and suggest that we enable also `description` and `title`, I can make a fix.

**Comment by SandMoshi** [comment]
You're right it is deprecated in the API but the API also states that things like description are grabbed from the meta tags in the <head> of the page. 

We should be able to pass the description as a prop to the component and then have the component append the description to the proper <meta> tag in the <head>

Such as 

`<meta property="og:title"              content="When Great Minds Don’t Think Alike" />`
`<meta property="og:description"        content="How much does culture influence creative thinking?" />`
`<meta property="og:image"              content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg" />`

**Comment by aautio** [comment]
I'm closing the issue as it seems that a solution was found for the original scenario.
