### ISSUE TITLE
throw error after installing

### ISSUE THREAD

**Issue by nileshgulia1** [nygardk/react-share#112]
after installing via <code>npm install react-share --save</code>.It shows punycode.js not found<br>
<code>Failed to compile.

./node_modules/punycode/punycode.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/nilesh/Desktop/my-app/node_modules/punycode/punycode.js'</code>

**Comment by aautio** [comment]
Try clearing your npm cache: `npm cache clean`or remove the `node_modules` folder and run `npm install` again. Does the problem persist?

**Comment by nileshgulia1** [comment]
I already solved my problem in the same way you mentioned,thanks anyways :)
