### ISSUE TITLE
Change MailShare to New Window

### ISSUE THREAD

**Issue by ernerock** [nygardk/react-share#113]
Could the EmailShareButton be changed to` window.open(link)` over `window.location.href = link `
to open it in a new window instead of having the user leave the page? 

Alternatively if for some reason someone wants it to be in the same page, give an option to use one or other.

**Comment by aautio** [comment]
`window.open("mailto:foo@bar.zap")` would open a blank white page/tab plus the email client of your operating system.

`window.open("mailto:foo@bar.zap", "_self")` might work without extra blank pages/tabs. But it should be verified with old IE's and some mobile browsers before taking that route.

Is there a downside to using `window.location.href = "mailto:foo@bar.zap"` -approach? It seems to be working.

**Comment by ernerock** [comment]
On mobile devices it works beautifully because it opens an email application, similarly it might open a desktop email application if installed(not tested).  In my case I use gmail web and if I share via email, it opens in the same page, leaving the website and preventing further engagement. A user would have to re-type the website url to go back to it.

Having said so I'm not sure anymore if this is a viable solution.
Browser compatibility seems to also be an issue since in IE the equivalent would be window.showModalDialog()

I'll close until i can come up with a better solution. Thanks you.

**Comment by yogeshR5** [comment]
Hi, @ernerock  did you got the solutions?  I'm facing the same issue right now.

**Comment by ernerock** [comment]
@yogeshR5 I did not pursue the issue. Most traffic I was receiving was mobile, hence had an email client listening to the mailto trigger. I considered browser detection to use own mailto component when on a desktop but wasn't worth my effort. I recommend doing this if you can't find any other solution. Good luck
