### ISSUE TITLE
 window is not defined

### ISSUE THREAD

**Issue by Itagiba** [nygardk/react-share#118]
I am trying to add your `react-share` module to an existing react application. I have added the contents of Demo.jsx into a component, however, whenever I try to run the APP and build it via the index.js file from which is imported I get the following error:

`ReferenceError: window is not defined`

I have been reading about this, and there appears to be something to do with it being rendered on the server, however, I see no simple way of fixing this issue as window it's present at every instance of your icon creation.

Any solution?

**Comment by MaralS** [comment]
Hi, 

I have the same issue. Did you find a solution ? 
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  "33 | }) {
  34 |   const { markdownRemark: post } = data;
35 |   const shareUrl = window.location.href;
     |                    ^
  36 |   const title = post.frontmatter.title; // data.markdownRemark holds our post data
  37 |   /*const hashtags = Array([
  38 |     'controletechnique', 'entretienauto', 'conseilsauto'


  WebpackError: window is not defined

  - blog-post.js:35 Template
    src/templates/blog-post.js:35:20

  - ReactCompositeComponent.js:306 ReactCompositeComponentWrapper._const    ructComponentWithoutOwner
    ~/react-dom/lib/ReactCompositeComponent.js:306:1

  - ReactCompositeComponent.js:282 ReactCompositeComponentWrapper._const    ructComponent
    ~/react-dom/lib/ReactCompositeComponent.js:282:1

  - ReactCompositeComponent.js:185 ReactCompositeComponentWrapper.mountC    omponent
    ~/react-dom/lib/ReactCompositeComponent.js:185:1

  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1

  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1

  - ReactDOMComponent.js:657 ReactDOMComponent._createContentMarkup
    ~/react-dom/lib/ReactDOMComponent.js:657:1

  - ReactDOMComponent.js:524 ReactDOMComponent.mountComponent
    ~/react-dom/lib/ReactDOMComponent.js:524:1

  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1

  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1


error Command failed with exit code 1."

**Comment by aautio** [comment]
@MaralS you need to check if `window` exists before accessing it in line 35 of your source file.

```js
if (typeof window !== 'undefined') {
  // you can access window.location.href safely:
}
```

**Comment by aautio** [comment]
@Itagiba I'm using server side rendering without problems with `react-share`.

Can you share an example code which displays the problem?

**Comment by MaralS** [comment]
@aautio I found an other way but i'll try again with your code if the error message disappears.
Thank you :)

**Comment by aautio** [comment]
Closing as solved.
