### ISSUE TITLE
Twitter share description 

### ISSUE THREAD

**Issue by AzzaRojbi** [nygardk/react-share#119]
I noticed that there is a quote prop for facebook and a description one for LinkedIn, is there any equivalent for Twitter? Now that a tweet has 280 characters, I think it makes sense to be able to share a description

**Comment by aautio** [comment]
You can use `title` prop and it will be prepended to the `url`. Here is a demo here: https://codesandbox.io/s/1838y69jn7

And here is the relevant code:

```jsx
<TwitterShareButton title='This is my tweet!' url={'http://www.google.com'}>
  <TwitterIcon size={32} />
</TwitterShareButton>
```
