### ISSUE TITLE
look like props logoFillColor is not working in react16

### ISSUE THREAD

**Issue by mnosuk** [nygardk/react-share#128]
Hi

This is my first issue on GitHub and I think I felt down on this hole

this is my code Example

```
<FacebookShareButton className="shareBtn" url={url}>
        <FacebookIcon size={32} logoFillColor="red" />
      </FacebookShareButton>
```

My Expect Behavior is There is a red 'F' in facebook icon but I got nothing happened.
is this library still work on react16?

actually I used my styled-components to workaround like this

```
const FacebookIconWhite = styled(FacebookIcon)`
  fill: white;
`

      <FacebookShareButton className="shareBtn" url={url}>
        <FacebookIconWhite size={32} />
      </FacebookShareButton>
```

it work, but do you think this is a good way? I think not.

**Comment by mnosuk** [comment]
in generateIcon.js around line 79

``` 
_react2.default.createElement('path', { d: iconConfig.icon })
```


look like you should add more key like this. 

`_react2.default.createElement('path', { d: iconConfig.icon, fill: color })
`

**Comment by nygardk** [comment]
#129
