### ISSUE TITLE
Component re-rendering unnecessarily

### ISSUE THREAD

**Issue by Ganasist** [nygardk/react-share#130]
I've been optimising across my app recently using ["why-did-you-update"](https://github.com/maicki/why-did-you-update)

It's triggering on react-share quite a bit:

`ShareButton.props: Value did not change. Avoidable re-render!`

Is there any way you could optimise this via PureComponent or shouldComponentUpdate?

**Comment by nygardk** [comment]
v2.0.0 uses PureComponent for share buttons
