### ISSUE TITLE
API change idea

### ISSUE THREAD

**Issue by rockchalkwushock** [nygardk/react-share#131]
## Problem

Most people probably want to use multiple social media api's to share with. An end user can end up with a pretty ridiculous amount of imports into a file and the component being built becomes very large in it's own right:

```jsx
import React from 'react'
import {
  FacebookIcon,
  FacebookShareButton,
  GooglePlusIcon,
  GooglePlusShareButton,
  LinkedinIcon,
  LinkedinShareButton,
  RedditIcon,
  RedditShareButton,
  TelegramIcon,
  TelegramShareButton,
  TwitterIcon,
  TwitterShareButton
} from 'react-share'
import { string } from 'prop-types'

const Share = ({ title, url }) => (
  <ShareList>
    <FacebookShareButton quote={title} url={url}>
      <FacebookIcon round size={32} />
    </FacebookShareButton>
    <GooglePlusShareButton url={url}>
      <GooglePlusIcon round size={32} />
    </GooglePlusShareButton>
    <LinkedinShareButton title={title} url={url}>
      <LinkedinIcon round size={32} />
    </LinkedinShareButton>
    <RedditShareButton title={title} url={url}>
      <RedditIcon round size={32} />
    </RedditShareButton>
    <TelegramShareButton title={title} url={url}>
      <TelegramIcon round size={32} />
    </TelegramShareButton>
    <TwitterShareButton title={title} url={url}>
      <TwitterIcon round size={32} />
    </TwitterShareButton>
  </ShareList>
)

Share.propTypes = {
  title: string.isRequired,
  url: string.isRequired
}

export default Share
```

## Proposed solution

I realize this would likely be a breaking change, but what are your thoughts on adding a `type` or `media` prop that accepts the social media type for the button/icons? It would mean the components would be generalized and display the appropriate icon & proper window display action for sharing.

### Proposed example

```jsx
import { ShareButton, ShareIcon } from 'react-share'

// props.list = ['facebook', 'google', 'reddit']

const SharePost = ({ list, url }) => list.map(type => (
  <ShareButton type={type} url={url}>
    <ShareIcon type={type} />
  </ShareButton>
) 
```

Obviously with some of the additional props pertaining to specific social api's there might need to be further discussion, but I think this would make the package more generalized in use for the end user and would dramatically reduce the number of exports from the package.

Looking forward to a discussion on this and I'm willing to work on the PR for this if it's something you feel is a good direction for the package.

**Comment by aautio** [comment]
I would assume that benefits from tree-shaking and small bundle sizes would be lost with this dynamic & generalized approach. 

Having a `Share` component as a part of your own app, as you've described, is a good approach I think. You can reuse your `Share` component all around your sites without re-importing all individual items from `react-share`. And it also solves the problems of additional props: they can be dealt within your `Share`-component.

**Comment by rockchalkwushock** [comment]
@aautio

I see what you mean now, agreed that it would break the tree shaking. I hadn't seen that `cjs`  & `es` modules are being output by the build. I'll stick with what I have. 

Closing.
