### ISSUE TITLE
EmailShareButton `url` is useless

### ISSUE THREAD

**Issue by amed** [nygardk/react-share#132]
As it is written here: 

https://github.com/nygardk/react-share/blob/master/src/EmailShareButton.js#L6

`url` is skipped with no action in `EmailShareButton`, how can we provide email body with this link ? There are other similar issues opened at this repo, maybe we can change `mailto:` ? any ideas ?

**Comment by theGABS** [comment]
Some problem. In doc you write "if body is empty will use URL" but it is wrong.

**Comment by aautio** [comment]
Yes, there is a mismatch with the props and the documentation. I'll prepare a PR to fix this in a few days.
