### ISSUE TITLE
Pintrest save error

### ISSUE THREAD

**Issue by punk0x29a** [nygardk/react-share#134]
When clicking on the pintrest share button, it displays correctly the picture I'm trying to share, description, and my Pintrest tables as well. But when I'm trying to save the pin, after a short moment of loading an error occurs:

`Sorry! Something went wrong on our end. Please try again.`

According to this topic: [https://wordpress.org/support/topic/pinterest-save-button-error-sorry-something-went-wrong-on-our-end-please-try/ ](url)

"Pinterest has deprecated anything but the addition of their code to your site. "

**Comment by aautio** [comment]
I am unable to reproduce your problem.

I am using Pinterest sharing and it is working ok. I just tested it with the demo site at http://nygardk.github.io/react-share/ and the end result looks ok: https://fi.pinterest.com/pin/545357836120870119/

Can you share more details/code/... about your problem?

**Comment by aautio** [comment]
Closing after two weeks of inactivity.
