### ISSUE TITLE
How do I get the twitter share count?

### ISSUE THREAD

**Issue by 21-Hidetaka-Ko** [nygardk/react-share#137]

**Comment by aautio** [comment]
Twitter share count is not provided by `react-share`. As far as I know the Twitter API does not provide a mechanism to fetch the share amount. 

For further information please see:
- https://twittercommunity.com/t/a-new-design-for-tweet-and-follow-buttons/52791/7
- https://twittercommunity.com/t/how-to-get-proper-twitter-share-count-for-a-url/53876/12
- https://stackoverflow.com/questions/35146281/twitter-get-number-of-shares-using-the-new-api
