### ISSUE TITLE
How to bundle without icons

### ISSUE THREAD

**Issue by third774** [nygardk/react-share#147]
I've tested this using `create-react-app` and `webpack-bundle-analyzer`, and it looks like all of the icons are being bundled. Is there currently a way to only bundle the imported components?

![code](https://user-images.githubusercontent.com/8732191/38450483-f0684a1e-39e3-11e8-9a02-74544eb7edad.png)

![image](https://user-images.githubusercontent.com/8732191/38450485-fd532ea6-39e3-11e8-92d0-8a70b6e70f2b.png)

**Comment by nygardk** [comment]
This is hard for me to test atm, but would you mind to do a following test yourself:
Find `react-share`'s `package.json` in `node_modyles/react-share` and add
```
sideEffects: false,
```
to it. Then try if the bundle is tree-shaked.

**Comment by aautio** [comment]
`create-react-app` uses webpack 3 and thus it does not yet support `sideEffects: false`. Once they've migrated to webpack 4 the `sideEffects: false` would solve the issue as well. I think we could add it to `package.json` immediately as there should not be any downsides and people running webpack 4 would benefit.


But for the moment you can import only the necessary components directly. This will skip icons and all other unnecessary files and yield a tiny bundle:

```
import FacebookShareButton from 'react-share/es/FacebookShareButton'
```

**Comment by third774** [comment]
Thanks, @aautio - that's what I was looking for!
