### ISSUE TITLE
Sharing Message

### ISSUE THREAD

**Issue by bradymwilliams** [nygardk/react-share#15]
Is it possible to pass a message to the component to prepend the link on share?

**Comment by nygardk** [comment]
I don't quite understand what you mean. Can you provide an example about what you are looking after?

**Comment by BlackSheepWithMe** [comment]
Sure,

So when you click the fb icon and the window pops up with  the link ready
to share. Normally you have an ability to PRE populate that text box with a
quick snippet of what to share =]

**Comment by nygardk** [comment]
It is probably not possible with the used sharer.php. Maybe @JoanBalder would like to create a PR of the  feature using Facebook feed dialog?

**Comment by JoanBelder** [comment]
I can send the PR for the feed dialog. It does not however enable you to pre-populate the actual message field for the user. I added a screenshot of what it looks like:
![feed-dialog-sample](https://cloud.githubusercontent.com/assets/775516/16146284/8fa9bac2-347d-11e6-98c3-ad8c48d52cfe.png)

**Comment by LucasKA** [comment]
@JoanBelder Please add this PR if you have the functionality running.

I've been looking for a comprehensive sharing component that allows sharing to the feed. I'm using this library on an image gallery where the images are shareable.

**Comment by nygardk** [comment]
I actually implemented the newer Facebook dialog sharing functionality already, but haven't added it yet. I'm not sure what would be the best way, since the dialog requires API key and a Facebook app. I'd imagine most of the library users do not want or need an API key. Opinions?

**Comment by JoanBelder** [comment]
The [facebook docs](https://developers.facebook.com/docs/sharing/reference/feed-dialog) suggest that that the `app_id` is a required field. However currently seems to just works fine without any app_id. So at the moment it wouldn't be any issue, but I'm not sure how likely this is going to change in the future.

**Comment by nygardk** [comment]
Yeah, `app_id` is what I meant. Good correction about it not really requiring it. I would imagine they are not going to change it without changing the API version, so we might just tie the implementation to the current newest version (v2.3 ?).

**Comment by LucasKA** [comment]
@nygardk I would suggest having _method_ as props, and if you use the "feed" option, you have to pass an _app_id_ prop along with it, but the component could default to the sharer.

**Comment by LucasKA** [comment]
If you PR your work I'll see if I can help.

**Comment by nygardk** [comment]
@LucasKA  I pushed the changes to branch `feature/facebook-dialog-sharing`. The sharing won't work as it gives error `Invalid App ID: 0`. So it seems it really needs the `app_id`.

**Comment by LucasKA** [comment]
@nygardk Correct, you need to create an app and pass an `app_id` in order to use the newer API sharing functionality.

**Comment by LucasKA** [comment]
I tested it with a real App ID and it definitely works.

Is this something you want to make polymorphic? Like, by default it uses the sharer, but if you provide "feed" as a method, and the extra props (App ID and Image URL), it will render with the Feed functionality?

<img width="896" alt="screenshot 2016-08-01 14 15 03" src="https://cloud.githubusercontent.com/assets/1824267/17309187/790b793e-57f2-11e6-954d-279ebd3cf8d4.png">

I don't want to break your API, but sharing a specific image is a common use case.

**Comment by HarshaVardhanPVK** [comment]
@LucasKA 
Is there any possibility to share image in facebook and twitter like you shown above. I want to share through my live facebook and twitter apps.

**Comment by LucasKA** [comment]
@HarshaVardhanPVK I needed the changes in the branch for work so I forked the repo and customized it.

Facebook works, but twitter doesn't have as robust an API, so I haven't been able to share "cards" the same way.
