### ISSUE TITLE
Module FacebookShareButton.js has no id

### ISSUE THREAD

**Issue by zozoens31** [nygardk/react-share#158]
While bundling my app with webpack 4.10.0, I got the following error:

> RuntimeTemplate.moduleId(): Module /usr/app/node_modules/react-share/es/FacebookShareButton.js has no id. This should not happen.

This makes the bundling process fail.

This didn't happen with previous versions of webpack (eg 4.9.1).

**Comment by nygardk** [comment]
Does it happen still with webpack 4.10.1?

**Comment by zozoens31** [comment]
No, it seems it was a bug on their side.
