### ISSUE TITLE
Viber

### ISSUE THREAD

**Issue by openlex** [nygardk/react-share#160]
Hello. Viber btn does not work in demo && vber component does not exist in code

**Comment by aautio** [comment]
@openlex I'm not familiar with Viber, but I think you need to have it installed in your mobile device in order for the button to work.

The button seems to trigger an url lik `viber://forward?text=...`.

Did you find a solution to this issue?

**Comment by bfintal** [comment]
Please re-open, viber doesn't work in the demo in Chrome iOS
