### ISSUE TITLE
twitter card preview doesn't work

### ISSUE THREAD

**Issue by FadiAboMsalam** [nygardk/react-share#168]
Hi all,
am using react-share and it is working as charm on **facebook** and **google**
however trying to tweet a link to my website **doesn't generate the twitter card preview** .
i thought it is bug for my website but i tried the demo on this github and i am receiving the same view which is like this 
![react-share-bug](https://user-images.githubusercontent.com/12826829/42465683-5f0b557c-83b5-11e8-8e42-0405844d3d5c.PNG)

am i missing something ?

**Comment by kgajowy** [comment]
👍 same issue, even with og:tags and twitter:<tags> provided

**Comment by aautio** [comment]
@FadiAboMsalam @kgajowy I think you are correct. Twittter does not provide the functionality. The Twitter Share dialog does not show a preview of the link.
