### ISSUE TITLE
Youtube Icon

### ISSUE THREAD

**Issue by tiaaaa123** [nygardk/react-share#17]
Hi, 

I'm currently using react-share to add icon to share  face/twitter/etc. page. The problem is that I have multiple page where I need a Youtube Icon like the others. I don't need to be able to share on Youtube, just the icon.

Could you add the youtube Icon to react-share?

**Comment by nygardk** [comment]
Hi,

The icons used are taken from https://github.com/jaketrent/react-social-icons (it is mentioned in the readme). Please use that or any other repository to your advantage.

It is not the purpose of react-share to include other than sharing-related icons, so I will not add it at the moment :).

**Comment by tiaaaa123** [comment]
Thanks alot! :D
