### ISSUE TITLE
FacebookShareButton and TwitterShareButton Add to imFacebook and Twitter did not find attributes for image sharingage attribute

### ISSUE THREAD

**Issue by XanderXueMingJi** [nygardk/react-share#176]
I have a need to share pictures with Facebook and Twitter, but I haven't found the attributes for sharing pictures. Could you tell me what to do?

**Comment by artsiomYavorski** [comment]
@XanderXueMingJi 
I've solved this issue by using 'og:image' meta tags inside my app pages. Facebook automatically grabs this data.
as example:
<meta data-rh="true" property="og:image" content="{image_url}">

**Comment by kdekooter** [comment]
@artsiomYavorski whoops you forgot the sample code

**Comment by aautio** [comment]
Here are good resources to help with images and other metadata:

- https://developers.facebook.com/docs/sharing/webmasters/
- http://ogp.me/
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
