### ISSUE TITLE
whatsapp sharing via desktop browser doesn't work

### ISSUE THREAD

**Issue by yhendry** [nygardk/react-share#179]
on desktop (i.e. using Firefox), upon clicking Whatsapp share icon, it will prompt this error in the pop up dialog:

> Firefox doesn’t know how to open this address, because one of the following protocols (whatsapp) isn’t associated with any program or is not allowed in this context.
> 
>     You might need to install other software to open this address.
i found a workaround, which is not to use api.whatsapp.com (because it will resolve to whatsapp:// , which the browser doesn't understand; instead use web.whatsapp.com when it detected as non-mobile device?)

**Comment by aautio** [comment]
This is a duplicate of #157 and it might get fixed when we have #194 merged.
