### ISSUE TITLE
Looks like the title prop is not required for facebook share?

### ISSUE THREAD

**Issue by GanbilegBor-minted** [nygardk/react-share#18]
How is the title prop being used for the facebook share? Looks like only url is being used for the constructing the popup url. I believe facebook figures out the title from the page's og:title or title metadata from their cache OR crawling the page again if no hit in their cache for this page.

I can create PR to change the doc but wanted to be sure before.

Let me know please and thanks,
- Ganbi

**Comment by nygardk** [comment]
Hi,

Good catch! Indeed, it is not used. Feel free to create PR!

thanks
