### ISSUE TITLE
ICONS NOT APPEARS ON CHROME IN PRODUCTION

### ISSUE THREAD

**Issue by briceth** [nygardk/react-share#183]
Hi guys,

The module is working on development mode, but once in production, icons are not appearing anymore (only in chrome). Even the demo is not working !

Regards

**Comment by aautio** [comment]
@briceth I've not been able to reproduce this. Can you share an example project setup where the icons would not be visible?

Do you see the icons in the demo site? http://nygardk.github.io/react-share/

**Comment by Anujraval24** [comment]
This is not working for me as well please give solution to this. @aautio
