### ISSUE TITLE
Linkedin title / description doesnt work?

### ISSUE THREAD

**Issue by luisfuertes** [nygardk/react-share#184]
I try to add title, description, summary, etc, but linkedint not show on share window. Only url. Any idea?

Example: 
```
<LinkedinShareButton url={shareLink} title={'title demo'} description={'description demo'} summary={'summary demo'}>
          <LinkedinIcon size={32} round={true} />
        </LinkedinShareButton>
```

Version:
`"react-share": "^2.3.0"` 

Image result: 
![captura de pantalla 2018-09-26 a las 17 17 30](https://user-images.githubusercontent.com/18212615/46090034-1aa18d00-c1b0-11e8-800b-3e6aa61f626e.png)

Thanks!

**Comment by malikshahzad228** [comment]
Any update on this?

**Comment by vsc-github** [comment]
Bump. Is there a workaround to this?

**Comment by vsc-github** [comment]
@malikshahzad228 Yep, checked that. Looks like there's no way to do it.

**Comment by malikshahzad228** [comment]
@vsc-github One way is to use LinkedIn developer rest API. But for that you have to signup as [LinkedIn partner program](https://business.linkedin.com/marketing-solutions/marketing-partners/become-a-partner/marketing-developer-program). Then you can generate LinkedIn developer app, and start using [rest APIs](https://developer.linkedin.com/docs/guide/v2/shares/share-api).

**Comment by umair-khanzada** [comment]
Is there any update on this ?

**Comment by bajayo** [comment]
As far as their documentation: https://developer.linkedin.com/docs/share-on-linkedin# the api seems to expect a "comment" field but the LI share button sends:
url,
title,
summary: description,

**Comment by rockbjornen** [comment]
When will @aautio's changes be merged and a new version published? Really would like this to work :)
