### ISSUE TITLE
How to use this package without it automatically including babel-runtime?

### ISSUE THREAD

**Issue by gitgrimbo** [nygardk/react-share#187]
I am providing my own polyfills elsewhere in my application, so don't want babel-runtime included.

![image](https://user-images.githubusercontent.com/1020541/47617485-6bfab000-dabf-11e8-81c9-99cae6da2cab.png)

**Comment by charlesswanson** [comment]
I had the same error as @Twansparant . I worked around it by using this package's babel-7 branch.

**Comment by nygardk** [comment]
Should not be an issue with v4.
