### ISSUE TITLE
Pinterest

### ISSUE THREAD

**Issue by schickling** [nygardk/react-share#2]
I saw you're currently working on the Pinterest sharing feature as well.

Any updates on this? :)

**Comment by nygardk** [comment]
Hi!

I was not working on it actively, but now that you asked I might implemented it soon -- perhaps in a week or so :). Let me know if you wish to have any other social media services, too.

**Comment by schickling** [comment]
Awesome! :+1:

**Comment by nygardk** [comment]
Pinterest support added in 1.2.0!
