### ISSUE TITLE
Fb share isn't working

### ISSUE THREAD

**Issue by carpben** [nygardk/react-share#203]
I added the library to a project a few days ago. Whats'app share works well, so does Twitter share, but Facebook share doesn't. I hoped this will be similar to [issue 8](https://github.com/nygardk/react-share/issues/8) (where it didn't work cause he was using the local server), so I tried loading it to a live server page. but the problem persists also on the server. 
When clicking the button 
![image](https://user-images.githubusercontent.com/13496178/50768506-5a850f80-1289-11e9-9673-8af27faed252.png)

a popup opens with an error page: "Sorry something went wrong". 

![image](https://user-images.githubusercontent.com/13496178/50768538-725c9380-1289-11e9-858d-cd2f1706fbf9.png)

When clicking the "go back" link it opens the main FB page:

![image](https://user-images.githubusercontent.com/13496178/50768646-d2533a00-1289-11e9-91c4-3775325a800b.png)

here is the code of the component: 
```tsx
				<FacebookShareButton
					url={url}
					quote={message}
					hashtag={hashtags[0]}
				>
					<FacebookIcon
						{...ICON_DEFAULTS}
					/>
				</FacebookShareButton>
```

besides children all the props I pass to FacebookShareButton are strings. Any idea why this bug is happening, and how I can solve it?

**Comment by aautio** [comment]
Hi @carpben, would you have the problematic page online somewhere? Can you share the url of it and I'll take a look.

**Comment by carpben** [comment]
Here it is: https://www.givingway.com/test_2.give

**Comment by carpben** [comment]
I prepared a demo: 
https://codesandbox.io/s/4jr208jm2x
https://4jr208jm2x.codesandbox.io/

**Comment by jupardo** [comment]
I've looked up into the error and I found that this error appears when you're using non existent url.

**Comment by carpben** [comment]
What do u mean by non existent url? Check https://codesandbox.io/s/4jr208jm2x. I'm using the url "https://github.com/nygardk/react-share/issues/8" which exists indeed.

**Comment by jupardo** [comment]
Well, i've found the problem.
If you're using hashtag property on fbshare button you must start the hashtags with "#"
I've forked your project and added # an it works.

https://codesandbox.io/s/ojn2x54jk9

**Comment by carpben** [comment]
@jupardo , thank you very much! I did not expect that.

**Comment by tensor-flower** [comment]
@jupardo Thank you so much! Been wondering why it didn't work!
