### ISSUE TITLE
Open share in new window instead of new tab

### ISSUE THREAD

**Issue by Bryze** [nygardk/react-share#204]
Is there an option to toggle the behaviour of the popup window?

For example - Whenever I click of the fb button, it currently navigates me to a new tab, but I want a new smaller window to open. The documentation says it's a popup, but I couldn't find any implementation around it?

Is it OS-dependent thing? I'm currently on a mac.

**Comment by thiloilg** [comment]
I would like to always open a new tab rather than a pop-up window. Is there a way to enable this behavior?

**Comment by nesbtesh** [comment]
Hi is there?

**Comment by lebenswald** [comment]
I am not sure why a new window is the default. It takes the user away from the main site much more than opening a new tab.

**Comment by kuroshhashemi** [comment]
There's a PR open for it: https://github.com/nygardk/react-share/pull/342.  Can't someone merge it?
