### ISSUE TITLE
Remount share buttons

### ISSUE THREAD

**Issue by Bryze** [nygardk/react-share#205]
I provide the share buttons a url from an api. Now, the initial url is www.google.com

I fetch the url from an api and update the url to be shared, but somehow the previous url is shared. Was wondering is there anyway to remount the component?

**Comment by Bryze** [comment]
More insight - So, apparently, the url doesn't change on the first execution. it resolves on the next executes.

For example - 
-i hit an api, fetch the url and set state the url
- window is opened after doing a resolve, but it navigates to the same initial url.
-  subsequent pop up navigate me to the set url

Why is this behaviour happening?

**Comment by nygardk** [comment]
Please let me know if the issue still persists `v4.0.0`.
