### ISSUE TITLE
Can I change meta image with another one? in FacebookShare

### ISSUE THREAD

**Issue by KyoungWan** [nygardk/react-share#206]
Hi , I want to share page with url and image.
but
when i set url with "https://google.com",  it always show google's image (meta image of google.com)
I just want to change that image with my custom one

like this way,,
```
<FacebookShareButton
      url="https://google.com"
      image="https://my-custom-image-url"
  <FacebookIcon size={100} round />
</FacebookShareButton>
```
Is it possible? or can you tell me any other solution?

In some reason, I cannot set meta tags in target url.
breifly, Is it possible setting sharing image with my custom one, not using meta of target page?

**Comment by aautio** [comment]
No, it is not possible. Facebook uses the image as defined in the meta tags of the target page.
