### ISSUE TITLE
Sharing a url on facebook with an array in query string ignores the array

### ISSUE THREAD

**Issue by yasserzubair** [nygardk/react-share#207]
The URL is want to share via facebook is this

https://example.com/compare?&propertyId=15165&propertyId=15143&propertyId=15134&propertyId=15110&compareType=residential

as you can see, it creates an array 'propertyId' in the react router which is processed to fetch data. However, when i share it on facebook via react share, I get this URL

https://example.com/compare?&propertyId=15110&compareType=residential&fbclid=IwAR22DUJRMx-F5gSmp7WeGoK6CZBtdm5Ap54jO4m6QcQgm6MqEZWfcztDbbc

this has only one propertyId parameter and not an array. Other query params for this string are skipped.

**Comment by yasserzubair** [comment]
Any update on this? @nygardk

**Comment by nygardk** [comment]
I cannot reproduce this issue and I think it's an issue of react-share.
