### ISSUE TITLE
Pocket share support

### ISSUE THREAD

**Issue by xuopled** [nygardk/react-share#213]
Hello, Do you plan to add a support to [Pocket](https://getpocket.com/) service to enable the reader to read later?

It could be awesome.

Maybe I can make a PR for you if you are interested.

What do you think?

**Comment by xuopled** [comment]
I just found #201. I hope it will be merged soon

**Comment by aautio** [comment]
I'll merge the #201 to be included with the upcoming react-share 3.0.0 👍

**Comment by xuopled** [comment]
Perfect, thank you 👌🏻
