### ISSUE TITLE
Maximum Call Stack Size Exceeded

### ISSUE THREAD

**Issue by baoist** [nygardk/react-share#22]
I was running into this issue a lot when using `brunch v2.3.0` and `babel-brunch v5.1.2`. First `maximum call stack size exceeded` was being thrown on importing `core-js` or `regenerate` from `babel-polyfill` (would change between the two frequently). It eventually turned out that the issue was with the `jsonp` import.

The solution was to use `brunch v2.4.x` with `babel-brunch v6.0.x`. _Note that `brunch v2.5.x-v2.8.1 (current head)` still had the issue present. I'm not exactly sure why in my digging, but if I have more time later I will update this._ 

This is probably a particularly rare bug to come across (and possibly exceeding the scope of this repo), so if you want to just immediately close it that's fine. It just seems note-worthy in case anyone else comes searching for it.

**Comment by nygardk** [comment]
Thanks for the info! I'm closing this and let's hope someone will find it helpful when running into similar issues.
