### ISSUE TITLE
Facebook title and description query params

### ISSUE THREAD

**Issue by GanbilegBor-minted** [nygardk/react-share#23]
I think facebook sharer.php accepts title and description query params, besides using the og:title og:description meta data from the crawled page. Any reason why they were omitted?

cc-ing @NickDueber-minted.

**Comment by nygardk** [comment]
Thanks for the notice! No reason why they were omitted -- I guess I just missed them.

`title` and `description` props for FacebookShareButton should now work in version `1.8.2`.

**Comment by GanbilegBor-minted** [comment]
👍
