### ISSUE TITLE
Is this repo still maintained ?

### ISSUE THREAD

**Issue by Gp2mv3** [nygardk/react-share#235]
Hi,
I was wondering if this repo is still maintained ?
There are some important Pull Requests waiting.

The one about Facebook is critical as Facebook has started contacting people using only "u" parameter.

Regards,

Gp2mv3

**Comment by Gibbo3771** [comment]
Welp that would explain why this is not working for me, I've been mainly implementing testing and such for my app and came across this issue.

**Comment by nygardk** [comment]
Hello,

Yes, it is still maintained :). See review in #234.
