### ISSUE TITLE
Include option to share in private message on Facebook

### ISSUE THREAD

**Issue by avrmb** [nygardk/react-share#246]
For some reason the option to "Share on private message" is not available when using the Facebook Share button. Could this be added?

I believe it is not a duplicate of #100 and #106 as I these propose a separate share button to Messenger, which is not what I propose.

**Comment by nygardk** [comment]
Added `FacebookMessengerShareButton` in `v4.0.0`.

**Comment by DenisGorbachev** [comment]
@nygardk Could you please mention that `FacebookMessengerShareButton` is available in documentation?
