### ISSUE TITLE
Callback when user has Tweeted?

### ISSUE THREAD

**Issue by olalonde** [nygardk/react-share#25]
I display the Share buttons as part of a modal and would like to automatically close the modal if the user has succesfully share the page on Twitter / FB, etc. I was wondering if there would be any way to add a callback prop to the share buttons which is called when one of the share popups closes.

**Comment by juliankmazo** [comment]
Or a promise better?
Cool feature to have anyway

**Comment by GiordanoArman** [comment]
This feature would be useful!

**Comment by nygardk** [comment]
Feature added (beforeOnClick property) in version 1.11.0.

**Comment by pbojinov** [comment]
This is especially useful from an analytics perspective on how many successful/failed/attempted shares have happened.

**Comment by kkseven07** [comment]
Any solutions on this problem?

**Comment by AtticusFetch** [comment]
Anyone got any luck with it? Maybe some workaround? Would really appreciate some info.

**Comment by parmesanking** [comment]
+1

**Comment by aautio** [comment]
You can use `onShareWindowClose` -prop to execute a callback when the window is closed. But there is no way to actually know if a user did tweet or not.
