### ISSUE TITLE
Share buttons are not working on a deployed Next.js static HTML site?

### ISSUE THREAD

**Issue by 5ervant** [nygardk/react-share#253]
Upon [exporting into static HTML app with Next.js](https://nextjs.org/learn/excel/static-html-export) and deploying it with GitHub Pages, clicking either of share buttons on that deployed Next.js static HTML site will do nothing even console log?

Do you think [Next.js fetching data for pages](https://nextjs.org/learn/basics/fetching-data-for-pages) hindering some scripts because I'm seeing some of this error?

    GET https://example.com/_next/static/aKwNyTHmBxvIg1FVyaUhd/pages/post/[slug].js net::ERR_ABORTED 404

**Comment by nygardk** [comment]
Unfortunately I cannot help with this one. I don't think it's an issue of react-share.
