### ISSUE TITLE
heroku deployed app URL not working with Linkedin option.

### ISSUE THREAD

**Issue by bhavik5** [nygardk/react-share#260]
I have tried to share URL using react-share on linkedin.

All URLs are going well, but herokuapp URLs are not working. All other free hosting domain URLs are also working. Any URLs of herokuapp are not working.

```
<LinkedinShareButton url="https://www.demosite.herokuapp.com/example?q=demo">
  <LinkedinIcon size={40} round={true} />
</LinkedinShareButton>
```

Any help would be appreciable

Thanks

**Comment by nygardk** [comment]
Please let me know if the issue still persists in `v4.0.0`.

**Comment by JulianPhillips** [comment]
I have this same error
