### ISSUE TITLE
onShareWindowClose not working properly

### ISSUE THREAD

**Issue by utkarshsanjivan** [nygardk/react-share#265]
When I am trying to use 'onShareWindowClose' property to determine if the user makes a post or closes the window after clicking on the submit button, the function that I assigned to it is not being called then instead it is called when the page loads like it should for 'beforeOnClick'.

What am I doing wrong?

**Comment by nirsgv** [comment]
I have exactly the same issue. 
Cant seem to reach the callback.

**Comment by mumispb** [comment]
Are you passing the function or the execution of it?

Say we have a function (using functional components):
`function functionName() {...}`

Wrong: (will be executed when page loads)
`onShareWindowClose={functionName()}`

Correct: (will pass the function to the property to be called when share window closes)
`onShareWindowClose={() => functionName()}` or `onShareWindowClose={functionName}`

**Comment by utkarshsanjivan** [comment]
I am passing as onShareWindowClose={functionName}.

**Comment by vivekssharma07** [comment]
@utkarshsanjivan  did you got any solution ,on how to determine whether a user posted a content or closes the window by onShareWindowClose 'property' ?

**Comment by nygardk** [comment]
I think two separate issues discussed here:
* the passed function is invoked immediately, which is likely due to incorrectly passed function to `onShareWindowClose` like suggested above
* being able to determine if user posted content via the share dialog: this is not possible to implement per my understanding
