### ISSUE TITLE
WeiboIcon is missing

### ISSUE THREAD

**Issue by martinratinaud** [nygardk/react-share#273]
Hi folks and thanks for this great library

I wonder why WeiboIcon is not present in this set

For now, I'm using an extension of your demo

```javascript
const WeiboIcon = styled('img').attrs({
  src: 'http://icons.iconarchive.com/icons/martz90/circle-addon2/512/weibo-icon.png',
  alt: 'Weibo share button',
})`
  width: 40px;
  margin-bottom: -5px;
`;
```

but I would be glad to submit a PR if necesary

**Comment by nygardk** [comment]
Not a valid issue anymore -> closing.
