### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by VapiSoft** [nygardk/react-share#274]
I tried to run 

I do:
`    return (<WhatsappShareButton url='http://localhost:3000/#/app/presents?id=143'/>)
`
I get
Uncaught (in promise) TypeError: util.inherits is not a function
    at Object.eval (assert.js:164)

I tried to add this before, but it didn't help
    inherits(WhatsappShareButton, EventEmitter);  //share_components.map(s => s);

Maybe the problem is that I am running it locally (localhost:3000) >

**Comment by VapiSoft** [comment]
What I learned is that this problem occures even if I just import a component.
import { FacebookShareButton} from 'react-share';
or
import FacebookShareButton from 'react-share';
I get the above error.

**Comment by crypteriumguy** [comment]
Experiencing the same issue.

**Comment by VapiSoft** [comment]
Thanks, please let me know if find a solution.
It is extremely important for me.

**Comment by VapiSoft** [comment]
The problem was that I had a folder name 'util'
Changed the folder's name and now it is OK.
