### ISSUE TITLE
Facebook ad warning: “it includes outdated facebook brand assets”

### ISSUE THREAD

**Issue by olalonde** [nygardk/react-share#28]
I recently tried to get an ad approved on Facebook and got a warning because "it includes outdated facebook brand assets". I believe it might be due to the Facebook share button that comes with react-share but am not entirely sure.

I was wondering if anyone else ran into this problem

**Comment by nygardk** [comment]
It _might_ be because the Facebook sharing button design is not according to the brand guidelines (see [https://www.facebookbrand.com](https://www.facebookbrand.com)).

Just to be safe, I updated the Google+ icon to match the newer Google logo design in version `1.8.5`.
