### ISSUE TITLE
Twitter includes an empty hashtag by default

### ISSUE THREAD

**Issue by ummwolfcat** [nygardk/react-share#284]
In `TwitterShareButton.ts` the `hashtags` param is an empty array by default. In this case, Twitter adds an empty hashtag to the tweet. The fix is to simply not provide the param if `hashtags` is an empty array.

This doesn't seem to be a problem on the web, but it's for sure a problem with Twitter's iOS app. Not sure about Android.

**Comment by ummwolfcat** [comment]
@nygardk is this a known issue?

**Comment by nygardk** [comment]
Fixed in v4.1.0
