### ISSUE TITLE
EmailShare brocken URL on Xiaomi Redmi note 4x

### ISSUE THREAD

**Issue by Mur77** [nygardk/react-share#285]
EmailShare crops URL on Xiaomi Redmi note 4x, note 7. 
Chrome 78.0.3904.108
Please see screenshots! Thank you!

![a1](https://user-images.githubusercontent.com/48102532/72905914-f91bcb80-3d39-11ea-8139-520a4278d5bc.png)
![a2](https://user-images.githubusercontent.com/48102532/72905955-0c2e9b80-3d3a-11ea-9eb5-0c91646d0110.png)

**Comment by nygardk** [comment]
Hello! I don't this is an issue of react-share.
