### ISSUE TITLE
G+ count is not working.

### ISSUE THREAD

**Issue by sushilk1991** [nygardk/react-share#3]
I am using react-share in my web app, everything is working fine except G+ count.

I am getting below error:

`Uncaught TypeError: Cannot read property 'metadata' of undefined`
`onSuccessdata @ share-count-getters.js:66`

**Comment by nygardk** [comment]
Hi,

Thanks for pointing out this issue.

Could you please elaborate the error a little bit:
1. which url are you trying to get the share count for?
2. which browser are you using?
3. does that happen for all urls you are trying to get count for?

Also, please post example code that raises this error.
