### ISSUE TITLE
Email Share Button

### ISSUE THREAD

**Issue by LucasKA** [nygardk/react-share#30]
Hey guys,

I started digging in your code to implement an email sharing button, and it seems like there's some work in there already for an email button.

Is this in the works or was it abandoned?

**Comment by nygardk** [comment]
Not in the works AFAIK. Isn't email sharing simply an `<a/>` tag? I don't immediately see the need to include it in this repository.

**Comment by LucasKA** [comment]
I ask because in `social-media-share-links.jsx` theres this exported function:

```
export function email(subject, body) {
  assert(subject, 'email.subject');
  assert(body, 'email.body');

  return 'mailto:' + objectToGetParams({ subject, body });
}
```

Which is halfway to that functionality.

**Comment by nygardk** [comment]
Oh, right. I had completely forgotten that I added it :). I was probably thinking of adding an email sharing button, too, but got other thoughts. I'll probably remove it in the next version.
