### ISSUE TITLE
Document how to create custom icons

### ISSUE THREAD

**Issue by thatneat** [nygardk/react-share#303]
The README says that this package "supports also custom icons" but doesn't say how. It'd be great to have an example of how to do that in the README and the demo page.

Specifically I'd like to just render a custom SVG, which can be used with the same signature as your other icons. The usage pattern would be something like:
```jsx
import { BaseIcon, TwitterIcon } from 'react-share';

const MyIcon = props => (
 <BaseIcon path='(some SVG path)' />
)

const AllMySocial = props => (
  <div>
    <MyIcon size=20 borderRadius=5 />
    <TwitterIcon size=20 borderRadius=5 />
  </div>
)
```

**Comment by pranavmodx** [comment]
I agree. I'm not sure how to add custom icons. I was looking for a workaround. @thatneat Did you have any success? Clearly 'BaseIcon' doesn't exist as of now.

**Comment by thatneat** [comment]
I just made my own simple element with a similar props to what's provided here. I only needed one icon that wasn't implemented here, and I didn't need many of the props provided here so I didn't even bother with a `BaseIcon`.

In my case it was as simple as 
```jsx
const InstagramIcon = ({ size }) => (
  <img
    src={instagram_logo_png}
    style={{ width: size, height: size }}
    alt="Instagram Logo"
  ></img>
);
```
and then I used it alongside other icons from this library.

**Comment by nygardk** [comment]
Hello! Supporting custom icons means that the buttons do not care what you pass as the children. Thus, this works:
```tsx
<FacebookShareButton ...>
  <ThisCanBeImageOfYourChoice />
</FacebookShareButton>
```

You can create any kind of image component or use any icon of your choice 🙂 .

**Comment by thatneat** [comment]
Hmm, that looks like pretty confusing code to me since the `Facebook` icon won't actually end up having anything to do with Facebook. It didn't even occur to me to use one of the pre-baked icons for a purpose other than what it says on it.

All that to say, IMO a `BaseIcon` would be a clearer way to go from a user standpoint.

Would you be against adding this to the documentation somewhere?
