### ISSUE TITLE
Share to Medium

### ISSUE THREAD

**Issue by tb42** [nygardk/react-share#308]
There's just about every cross-device channel on here, with the exception of Medium. Now that Medium has a substantial number of users, it would make sense to add sharing to Medium as a functionality.

**Comment by nygardk** [comment]
Hey! PRs for adding Medium are welcomed 👍 !

**Comment by amyrlam** [comment]
I can add Medium on here - have a use case! Will take a look and submit a PR

**Comment by amyrlam** [comment]
Ah, just realized I have a different use case for this so am abandoning ship, apologies!

**Comment by bnteau** [comment]
Hi! This issue has been closed but is there any solution to share on Medium? It would be nice to have this option 😄
