### ISSUE TITLE
It's posible can I change div to a href

### ISSUE THREAD

**Issue by i-ked-ii** [nygardk/react-share#309]
change` <div></div>` to `<a href="#"></a>`
<img width="1112" alt="Screen Shot 2563-04-21 at 16 27 26" src="https://user-images.githubusercontent.com/23306577/79849714-0bff7400-83ed-11ea-8527-1b7dec5efeb8.png">

to

<img width="854" alt="Screen Shot 2563-04-21 at 16 26 54" src="https://user-images.githubusercontent.com/23306577/79849739-16217280-83ed-11ea-934c-a17ca0b95757.png">

**Comment by nygardk** [comment]
Hello! This is not supported. Moreover, you are probably using an old version of `react-share`, since the share buttons are `button` elements in the newest version.
