### ISSUE TITLE
Can we exclude the url when sharing?

### ISSUE THREAD

**Issue by D-i-l-r-u-k-s-h-i** [nygardk/react-share#330]
I want to share only a piece of text and it does not include a URL. Can we use 'react-share' to only share text, omitting the URL?

**Comment by jjrchrds** [comment]
Having the same issue. url is required.

**Comment by D-i-l-r-u-k-s-h-i** [comment]
> Having the same issue. url is required.

I was able to get this to work by adding '' (blank quotations) for the URL.
