### ISSUE TITLE
Usage of assert from nodejs in components

### ISSUE THREAD

**Issue by Klynger** [nygardk/react-share#333]
Hey guys, how are you? 

I've been working on a project and we are using your library, but we encounter some problems because of the usage of `assert` that is from NodeJS and you guys use it in your components. Webpack adds mocks and polyfills (and I'm using Webpack) to these calls, but we are turning off NodeJS mocks to reduce the bundle size. 

So I would like to know if you guys could change the implementation and use maybe `console.assert` or implement an `assert` method?

Thank you (:

**Comment by nygardk** [comment]
Hey!

Thanks for pointing it out. I will fill fix it!

**Comment by nygardk** [comment]
Fixed in [`v4.2.1`](https://github.com/nygardk/react-share/releases/tag/v4.2.1)!
