### ISSUE TITLE
doesnt support npm2?

### ISSUE THREAD

**Issue by ZeroCho** [nygardk/react-share#35]
I use Google App Engine for my website, and it uses npm version 2.14.4. But this package supports npm3, so warning message comes out when installing this package.

`npm WARN engine react-share@1.8.5: wanted: {"node":">=4.0.0","npm":">=3.0.0"} (current: {"node":"4.1.2","npm":"2.14.4"})`

**Comment by neeharv** [comment]
@ZeroCho seems to be just a warning. Installs fine for me locally with npm2.
