### ISSUE TITLE
bug: optional prop title in conflict with browser html attribute

### ISSUE THREAD

**Issue by HawkeyePierce89** [nygardk/react-share#367]
Many components from `react-share` have an optional props `title` and it is in conflict with browser html attribute

<img width="322" alt="image" src="https://user-images.githubusercontent.com/25603805/101434744-32423780-391c-11eb-8e9f-b1a91537cbd1.png">

Is it possible to fix this, but save the option to set browser html attribute? I mean separate optional prop and html attribute

**Comment by nygardk** [comment]
`htmlTitle` prop has been added in [`v5.1.0`](https://github.com/nygardk/react-share/releases/tag/v5.1.0).
