### ISSUE TITLE
Share count is not working

### ISSUE THREAD

**Issue by olalonde** [nygardk/react-share#37]
It seems that none of the share counts are working... In my console I'm also not seeing any external http requests of any sort that would load that number.

**Comment by olalonde** [comment]
Tried calling facebook api manually with endpoint generated by getFacebookShareCount and got this:

https://api.facebook.com/method/fql.query?format=json&query=select%20like_c…here%20url%20%3D%20'http%253A%252F%252Flocalhost%253A3000%252Fc%252FdNpmVz

```
{
"error_code": 12,
"error_msg": "REST API is deprecated for versions v2.1 and higher (12)",
"request_args": [
{
"key": "method",
"value": "fql.query"
},
{
"key": "format",
"value": "json"
},
{
"key": "query",
"value": "select like_count, share_count from link_stat where url = 'http%3A%2F%2Flocalhost%3A3000%2Fc%2FdNpmVz'"
}
]
}
```

**Comment by nygardk** [comment]
Hi, thanks for reporting this.

It seems, that a new method to fetch share counts from the Facebook has to be implemented. I'll look into this over the weekend.

**Comment by nygardk** [comment]
This seems to work:
[http://graph.facebook.com/?id=http://github.com](http://graph.facebook.com/?id=http://github.com)
