### ISSUE TITLE
How to configure a Twitter card type and image?

### ISSUE THREAD

**Issue by LukeSwart** [nygardk/react-share#41]
How can I customize the card that is shared using Twitter with `react-share`? Twitter suggests using HTML `meta` tags for configuring and adding images to their share cards. For example, I'm trying to use the "summary_large_image" card type, as described here: https://dev.twitter.com/cards/types/summary-large-image

So I basically want to add these meta tags to my page:

```
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Parade of Fans for Houston’s Funeral">
<meta name="twitter:image" content="http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg">
```

To make this work with react using `react-share`, I am doing the following:

```javascript
import {Component} from "react";
import Helmet from "react-helmet";
import {ShareButtons, generateShareIcon} from "react-share";
import styles from "./test.css";


class Test extends Component {

  render() {
    const title = "I wanna share this!";
    const {
      TwitterShareButton,
    } = ShareButtons;
    const TwitterIcon = generateShareIcon('twitter');

    const url = this.getShareUrl();

    return (
      <div className={styles.shareHeader}>
        <Helmet
           meta={[
             {"name": "twitter:card", "content": "summary_large_image"},
             {"name": "twitter:title", "content": "Parade of Fans for Houston’s Funeral"},
             {"name": "twitter:image", "content": "http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg"}
           ]}
          />
        <div className={styles.socialShares} style={{display: 'flex'}}>
          <TwitterShareButton url={url}
                              title={title}
                              hashtags={['test', 'test2']}
                              >
            <TwitterIcon size={32}/>
          </TwitterShareButton>
      </div>
    )
  }
}
export default Explorer;

```

but the sharing page that appears after clicking the Twitter button doesn't have any of the information from my meta tags. How can I pass this information to `react-share`?

I think the solution here would also solve a similar problem with Facebook's sharing page, which uses the [OpenGraph meta tags](https://developers.facebook.com/docs/sharing/webmasters).

**Comment by LukeSwart** [comment]
After further investigation, it looks like this issue isn't with `react-share`, but instead it has to do with adding meta tags and allowing bots to parse the page.

I am currently solving this issue by adding my meta tags via `react-helmet` and pre-rendering the page via prerender.io. Hopefully this helps somebody!

Closing this issue for now.

**Comment by matewilk** [comment]
Is this a complete example ? I'm trying to `react-share` with an image on the client side only. I have a standard `index.html` file, and I included `react-helmet` into my component that is suppose to display the iframe share with an image.

I tried many variations with `property`, 'name` etc, still nothing.

Render method looks like this:

```javascript
render () {
    const {
      TwitterShareButton
    } = ShareButtons;
    const TwitterIcon = generateShareIcon('twitter');

    let shareUrl = 'http://example.com';
    let title = 'Title for the tweet';
    return (
      <div className='twitter-share-button-container'>
      <Helmet
        base={{href: `${window.location.path}`}}
        title="My Title"
        meta={[
          {"name": "twitter:card", "content": "summary_large_image"},
          {"property": "twitter:site", "content": "@rinsify"},
          {"property": "twitter:title", "content": "Spin up your addiction"},
          {"property": "twitter:description", "content": "description"},
          {"property": "twitter:image", "content": "http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg"},
          {"property": "og:image", "content": "http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg"}
        ]}
        />
        <div className='share-text'>
          <Subheader >share</Subheader>
        </div>
        <TwitterShareButton
          url={shareUrl}
          title={title}
          hashtags={['test', 'test2']}>
          <TwitterIcon
            size={32}
            round />
        </TwitterShareButton>
      </div>
    );
  }
```

The share window is of course displayed, but there is no difference no matter if I use `helmet` or not.

Any help much appreciated.

Thanks!

**Comment by buddies2705** [comment]
Did you solved the problem?
