### ISSUE TITLE
Option to override the `onClick` handler?

### ISSUE THREAD

**Issue by LukeSwart** [nygardk/react-share#42]
When we want to dynamically populate our meta tags, which are parsed by our social media bots like Twitter/Facebook/etc, it often takes a couple seconds for those tags to be generated. This is because we are using a solution, as outlined in this post:

http://stackoverflow.com/questions/39445108/how-to-dynamically-render-meta-tags-for-social-share-button-on-a-static-site

in which case we need to wait for an html file that contains our metatags to be uploaded to and S3 bucket before react-share triggers the provided url to be parsed by our social media bots. But react-share immediately triggers the social media bots to parse the provided url when the button is clicked. 

To solve this problem, I think we need an ability to override the `onClick` event handler function in a way that will prevent react-share from parsing the url until we are sure that our html file has been uploaded. The most reasonable way that I can see to do this is to override the `onClick` handler, and call `this.onClick` inside of our custom `onClick` handler when our metatags are ready to be parsed.

Also, here is a useful SO post that outlines some ideas about overriding the event handler function of a react component:

http://stackoverflow.com/questions/21180550/how-to-override-event-handler-function-of-child-component-from-parent-component

That post summarizes this issue in that we'll need to customize the `ShareButton` component to accept a custom `onClick` event handler, because React's "one-way data-flow" doesn't allow us to bind handlers outside of the child component.

**Comment by nygardk** [comment]
Hi,

Sounds like a good and valid use case.

However, I'm a bit hesitant of allowing overriding the onClick handler. I would propose `beforeOnClick` prop that would take a function that returns a promise. When the promise is resolved, the onClick action would be fired. Howd that sound?

The problem with onClick handler is that you would manually have to open the popup window. The onClick function would take at least 3 arguments, e.g. `event, value, windowOptions`.

**Comment by lonelydatum** [comment]
Is it possible to pass data to the promise when resolved. EX) 
new Promise( (good, bad)=> {
 setTimeout( ()=>{
good("https://my_new_url.com")
}, 2000 )
})
