### ISSUE TITLE
Required Prop title in Facebook Share button

### ISSUE THREAD

**Issue by nahushfcc** [nygardk/react-share#48]
Why is `title` a required prop in FacebookShareButton? I rendered a facebook share button and it gave me an error 
```
warning.js:36 Warning: Failed propType: Required prop `title` was not specified in `CreatedButton`
```
At first I count make out what i did wrong in my code and upon further investigation i figured it out. 
I just wanna know what was the purpose behind keeping the title prop as required in the FacebookShareButton

**Comment by nygardk** [comment]
Fixed in v1.10.2.
