### ISSUE TITLE
Twitter share button doesn't work on Android 12

### ISSUE THREAD

**Issue by sakabar** [nygardk/react-share#484]
# Problem

I put this button on my web site, and pushed it on Android 12.
Twitter application opened automatically, but the following message was shown.
> The term you entered did not bring up any results. Please try again later.

# Cause
The url of TwitterShareButton
https://github.com/nygardk/react-share/blob/454860844d11d11d23112db1982feaf0ef4f1f09/src/TwitterShareButton.ts
```
    'https://twitter.com/share' +
```

According to the Twitter help page, the correct share url is `https://twitter.com/intent/tweet` . 

[Twitter help page] How to add the Tweet button to your website
https://help.twitter.com/en/using-twitter/add-twitter-share-button

Make a share button with the explained way. The url path of the share button is `https://twitter.com/intent/tweet? ...` .

When we access `https://twitter.com/share`, then it automatically redirect to  `https://twitter.com/intent/tweet` normally.  However, this doesn't work on Android OS.

**Comment by sakabar** [comment]
I made a PR #485 for this issue.
I would be happy if you could merge this and publish a new version of react-share on npm.

**Comment by R-Peleg** [comment]
Did anyone manage to implement a workaround? I experience the same phenomenon in my application.

**Comment by nipun-threestops** [comment]
> Did anyone manage to implement a workaround? I experience the same phenomenon in my application.

me also facing same problem.

**Comment by carlos-ssh** [comment]
**Ey! anyone knows if is it fixed?**
I'm facing the same error with these buttons: `twitter.url`, `pinterest.url`, `tumblr.url`

**Comment by Ciaran0** [comment]
I have forked the repo with a fix for the twitter share. 
I don't plan to actively maintain this fork but feel free to use it.
`@ciaran0/react-share`

**Comment by reply2sagar** [comment]
please fix this asap. Everyone is having this issue!! https://github.com/nygardk/react-share/pull/485 needs to be merged

**Comment by davidosaro** [comment]
Please just checking if this issue has been fixed

**Comment by sakabar** [comment]
@rhtaylor  I'm just waiting for merging #485.

If you're in a hurry, you can use a forked repo.
https://github.com/nygardk/react-share/issues/484#issuecomment-1607217255

**Comment by Alfrex92** [comment]
@sakabar it doesn't work for Android 12,13 and 14 (webview) 😢 . Any idea how to fix it?

**Comment by marcinzygan** [comment]
any chance on fix for this  ? please :(

**Comment by nygardk** [comment]
Hey, this has been fixed in version `5.0.2`.

**Comment by sakabar** [comment]
@Alfrex92 Sorry, I'm not sure. This issue is closed. So it might be a good idea to make a new issue for the problem.
