### ISSUE TITLE
Adding notation or link to original website

### ISSUE THREAD

**Issue by ammark47** [nygardk/react-share#5]
Hi,
I was wondering if we could add a default message or link back to the website that originally referred the url.

**Comment by nygardk** [comment]
Hi,
I don't quite understand what you are looking for. Could you provide an example?

**Comment by ammark47** [comment]
Sure, 
I've added a screenshot of what I mean. I'm not sure it would be possible
![screen shot 2016-01-18 at 1 09 38 pm](https://cloud.githubusercontent.com/assets/12992026/12398935/d172104a-bde4-11e5-805c-d2b4145fcf91.png)

**Comment by nygardk** [comment]
I'm not sure if that is possible (probably is!). At the moment I do not have time to put into this, but I will queue this request for the next update (in unknown point in future).

Community support is also welcomed :).
