### ISSUE TITLE
google share count doesn't work

### ISSUE THREAD

**Issue by ZeroCho** [nygardk/react-share#50]
`Uncaught TypeError: Cannot read property 'metadata' of undefined(…)`

share-count-getters.js 67
```
xhr.onload = function onSuccessdata() {
  var data = JSON.parse(this.responseText);
  callback(!!data ? data.result.metadata.globalCounts.count : undefined);
};
```
data.result is undefined

**Comment by nygardk** [comment]
Please provide more information about when and how this happens.

**Comment by ZeroCho** [comment]
It doesnt happen anymore. I guess it was temporary problem of google api
