### ISSUE TITLE
Support hashtag for Facebook button

### ISSUE THREAD

**Issue by geloescht** [nygardk/react-share#56]
Facebook now supports adding one (!) hashtag to the user's message, via the hashtag parameter. This is unfortunately only documented to work via the SDK but actually also works with sharer.php.
See here for SDK docs:
https://developers.facebook.com/docs/sharing/reference/share-dialog
Try this link:
https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&src=sdkpreparse&hashtag=%23yolo

**Comment by nygardk** [comment]
Feature added in version 1.11.0.
