### ISSUE TITLE
Facebook picture

### ISSUE THREAD

**Issue by beersoup** [nygardk/react-share#59]
Hi, In my Facebok share never got picture show up when Im sharing, anyone have this issue?

**Comment by siddhant91** [comment]
I am having the same issue , i tried the demos folder and successfully post the github.com , but the picture never gets posted

**Comment by nickbae91** [comment]
Yup, having the same issue here. Trying to use the "picture" parameter to a url of the image, and it's not working. I know the url is right, because it works with a simple test with the <img> tag - it has to be either:

a) I'm not understanding what the "correct format" of the image path/url is supposed to be entered to the react-share component, or

b) It's a problem within the react-share library.

**Comment by Tobi2705** [comment]
Same issue here! Package working super fine, so would be great to find a solution for this

**Comment by Yurickh** [comment]
Apparently Facebook doesn't accept the image by URL parameter anymore.
In order to show the thumbnail, put this into your page's head:

```html
    <meta property="og:image" content="your-image.jpg">
    <meta property="og:image:secure_url" content="your-image.jpg">
```

Using this, your site will use `your-image.jpg` as thumbnail even when posting the link in slack, for example.

**Comment by gss-patricia** [comment]
The same issue for me. Even though I put Open Graph, the image does not appear.

**Comment by menervilles** [comment]
Indeed, I noticed the not required parameters for FacebookShareButton are not working. It seems the informations (image/description/title) are build automatically by facebook robots while crawling the URL.

**Comment by aert** [comment]
https://stackoverflow.com/questions/20956229/has-facebook-sharer-php-changed-to-no-longer-accept-detailed-parameters

**Comment by nygardk** [comment]
`picture` param is no longer supported by share.php. As posted above, please use `og` meta tags to get images showing when sharing stuff.
