### ISSUE TITLE
util.inherits is not a function webpack 2

### ISSUE THREAD

**Issue by crisys11** [nygardk/react-share#64]
i have the next error when i try to include react-share in my app, all compile fine and if i go to another routes where no is loading this library works fine, but when i include it crash.

TypeError: util.inherits is not a function
i am using webpack dev server with webpack 2. i am mocked the next modules

note: i tried to mock utils so because util is not defined in not node env.

node: {
    fs: "empty",
    child_process: "empty",
  },

**Comment by crisys11** [comment]
please see https://github.com/webpack/webpack/issues/1019

**Comment by crisys11** [comment]
this is an issue of util, a circular dependency between util and inherits packages. https://github.com/defunctzombie/node-util/issues/10

i work around npm i --save util@0.10.0 utils

**Comment by dziamid** [comment]
Updating inherits library to 2.0.3 solved the issue for me:
https://github.com/defunctzombie/node-util/issues/17
