### ISSUE TITLE
Can I add an image in Twitter share button 

### ISSUE THREAD

**Issue by ghost** [nygardk/react-share#65]
The same as the title
For now i just can share links or messages with parameter, i used the meta parameter in html header

``` html
<meta property="og:image" content="path-to-my-image.png">
```

But it doesn't work, then I tried to edit the share-button.js with no results either 

Anyone knows how to do that or a video or any media?

Thanks in advice 👍

**Comment by Im-Goutham** [comment]
Same question from me.How to share different images to twitter.

**Comment by aautio** [comment]
Twitter supports a wide set of `meta`-tags. This might help you to get started: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

@Im-Goutham would the link above help you to get images showing up in shares?

**Comment by aautio** [comment]
Closing after two weeks of inactivity.

**Comment by suman7063** [comment]
how to show image preview at twitter
