### ISSUE TITLE
Questions: Waiting for API data before opening the social share box

### ISSUE THREAD

**Issue by vget98** [nygardk/react-share#66]
Hi, I am having an issue with an async problem. For my use case I have an element on the site that gets turned into an image and saved to a 3rd party storage site and then returns a url for the image. But I need to react-share popup not open until it successfully returns the url. I tried using beforeOnClick but the social share popup box opens before the promises for the beforeOnClick have finished. Is there a way to make sure the beforeOnClick returns data before the pop up box opens?

**Comment by vget98** [comment]
Another workaround would be if I could trigger the opening of the social share dialog myself so I could make sure it only opens up after the image has been successfully saved. Do you guys exposed that for everyone to us or is there something I could change in the lib to make that happen.

**Comment by vget98** [comment]
I figured it out, you can just ignore this

**Comment by ahornerr** [comment]
@vget98 How did you resolve this?

**Comment by vget98** [comment]
@ahornerr this was a mistake on my part I did not properly return the for the async call promise and use .then. The beforeOnClick was all I needed

**Comment by Flamesh** [comment]
In this case. I create a ref to share button. After api response data, just use ref.current.click();
