### ISSUE TITLE
Make just Facebook, Twitter, Pinterest Icon turn into a cursor pointer. 

### ISSUE THREAD

**Issue by xih** [nygardk/react-share#68]
My code right now:

const SocialMediaSharing = (props) => (
  <div>
    <div style={styles.sharing} className='container'>
      <FacebookShareButton url={'google.com'} style={icon}>
        <FacebookIcon iconBgStyle={fillColor} size={32} logoFillColor='black' round={true} />
      </FacebookShareButton >
      <div style={icon}>
        <TwitterShareButton url={'google.com'}>
          <TwitterIcon iconBgStyle={fillColor} size={32} logoFillColor='black' round={true} />
        </TwitterShareButton>
      </div>
      <div style={icon} >
        <PinterestShareButton url={'google.com'} media='https://vice-sundry-assets-cdn.vice.com/sites/web-assets/vice-og.png'>
          <PinterestIcon iconBgStyle={fillColor} size={32} logoFillColor='black' round={true} />
        </PinterestShareButton>
      </div>
    </div>
  </div>
)

renders 
![image](https://cloud.githubusercontent.com/assets/8076886/24919332/9cbc2ea6-1ee3-11e7-935b-3c9966fa7a33.png)

however I want only the facebook, twitter, and pinterest icons to have the pointer turn into a cursor. 

I have added the css in icon, but that makes the whitespace in between the icons to turn into cursors. Any thoughts ? 

Thanks

**Comment by nygardk** [comment]
Simply add `className` property to the icons and provide `:hover` state in CSS accordingly.
