### ISSUE TITLE
Facebook Graph API limit reached

### ISSUE THREAD

**Issue by xuopled** [nygardk/react-share#70]
Hello, sometimes when I request Facebook counts, I get this error : 
```
{
   "error": {
      "message": "(#4) Application request limit reached",
      "type": "OAuthException",
      "is_transient": true,
      "code": 4,
      "fbtrace_id": "E+h93KlSgIM"
   }
}
```

Is there a way to add an api key to extends or control the limit ?

**Comment by aautio** [comment]
The share count queries to Facebook are done without any api keys.

I'm closing the issue to clean out older issues with no apparent solution.
