### ISSUE TITLE
Are these buttons supposed to work on mobile devices?

### ISSUE THREAD

**Issue by dschu-lab** [nygardk/react-share#75]
Because right now they don't work on iOS 10.3.1
I haven't had the time to debug this using the Safari Developer Tools, as I'm on mostly working on Linux.

**Comment by mddanishyusuf** [comment]
it's not working with the mobile devices. same here I'm getting the same issue. @dschu-lab if you fixed the issue. So, please let me know.

Thanks

**Comment by bwobst** [comment]
Still not working on iOS 11 Safari. Any update here?

**Comment by nygardk** [comment]
Seems to work on iOS 11.2.2. According to dev tools my ad blocker blocks some of the opening windows, but yeah, that's because of the blocker.

**Comment by sedubois** [comment]
@nygardk for me it does not work for me on iPhone iOS 11.4.1 with Firefox 13.2, even when the option "Block popup windows" is deactivated in Firefox. I tested with [this site](https://gatsby-starter-hero-blog.greglobinski.com/like-nonsense/) by clicking the Twitter share link at the bottom. That button works as expected from the same device with Safari.

**Comment by RobIsHere** [comment]
Hi @sedubois! Could you "persuade" Firefox mobile to work as expected somehow? Thank you!

**Comment by sedubois** [comment]
No and yes @RobIsHere; there's no solution to ensure it works for all Firefox users, but works when switching off "anti-tracking protection" in Firefox settings.
