### ISSUE TITLE
Facebook sharing is not working

### ISSUE THREAD

**Issue by buaya91** [nygardk/react-share#8]
Hi ~ 

Facebook share button is not working, did I make any mistake?

```
<FacebookShareButton url={url} title={title}>
     <FacebookIcon size={32} round />
</FacebookShareButton>
```

**Comment by nygardk** [comment]
Hi,

Can you elaborate how it is not working? Does anything happen when you click the button?

Double check that you are doing it as in the [demo](https://github.com/nygardk/react-share/blob/master/demos/demo0/Demo.jsx).

**Comment by buaya91** [comment]
@nygardk 
Thanks for your prompt reply, yes I was following the demo

Here's the popup 

<img width="947" alt="screen shot 2016-04-25 at 9 08 54 pm" src="https://cloud.githubusercontent.com/assets/6303687/14784805/fed86100-0b29-11e6-8edb-b84316d0e7d8.png">

Or do I need to register my host domain in facebook?

Btw, thanks for building this easy to use Component

**Comment by nygardk** [comment]
It seems you are trying to share a webpage from your local environment. Facebook of course cannot access that page, but it is strange that they are returning error 500. Try configuring it with a valid web address (like http://github.com). If that works, you can safely assume that your link sharing will work in production mode when you don't have localhost in the url.

**Comment by buaya91** [comment]
@nygardk 

That was indeed the problem, thanks for your help ~
