### ISSUE TITLE
Whatsapp share text undefined.

### ISSUE THREAD

**Issue by arjunkathuria** [nygardk/react-share#84]
Hi !
Great little lib : )

i am facing a small issue that, when i share from the whatsapp button, it ends up displaying the following in the whatsapp text input.

```
undefined
{the url i shared}
```

i don't know why this undefined is there. Does it search for a specific meta tag it cant find ?

**Comment by Method-X** [comment]
I'm having this issue with Facebook and Google (haven't tried WhatsApp). I don't think I'm doing anything wrong on my end.

**Comment by tarokawada26** [comment]
Having the same problem as @arjunkathuria :(

**Comment by tarokawada26** [comment]
@arjunkathuria not sure if you solved it already but you have to have title in your WhatsappShareButton

**Comment by aautio** [comment]
Solved by #120.
