### ISSUE TITLE
Successful share callback

### ISSUE THREAD

**Issue by kkseven07** [nygardk/react-share#87]
Such callback will be very useful(closing modal, make a discount, analytics).

**Comment by benoneal** [comment]
Can't upvote this enough

**Comment by jasan-s** [comment]
would love this feature

**Comment by AtticusFetch** [comment]
Anyone got any luck with it? Maybe some workaround? Would really appreciate some info.

**Comment by bogdanmarin** [comment]
For each ShareButton, you can add this beforeOnClick event. Worked for me

 <FacebookShareButton beforeOnClick={this.share.bind(this)} ...............

**Comment by bogdanmarin** [comment]
Update: My code is not doing the what @kkseven07  asked which is after share is successful not before.
I have the same need and  I'm thinking to replace the library if this will not be added. We can't do our scenarios without it. If anyone has a workaround let us know..

**Comment by nygardk** [comment]
I don't know what would be a solution to this. If you know another library that has this kind of functionality, I'd be really interested to take a look if it could be implemented in `react-share` as well.

You can already use `onShareWindowClose`. As the actual sharing is not done with XHR's, it would be really hard to know whether the user shared anything succesfully or not.

**Comment by MichelCreatingDev** [comment]
Is this issue not solved yet?
I need to know if the user shared anything successfully or not to count the shares.
onShareWindowClose is not correct for this.
Please help me.

**Comment by luisfuertes** [comment]
+1

**Comment by lastgiven** [comment]
+1

**Comment by ZemtsovIgor** [comment]
+1

**Comment by dpmango** [comment]
Is it possible to make a request after onShareWindowClose to see if a specific user has shared this post or counter has increased since user closed window?

**Comment by kkseven07** [comment]
Seems like the developer of the library is not working on it. If anyone finds a better library, share please.

**Comment by shivasai09** [comment]
+1

**Comment by aautio** [comment]
The `react-share` is focused on share buttons and share counts. It requires no server and thus it is lightweight to set up.

Trying to solve this issue would require service specific integrations and some black magic to make happen: It is not in the nature of Facebook, Twitter and others to make it easy for an 3rd party to query what a specific user has shared or done in their service.

I'm closing the issue as there is no new solutions in sight. Please use `onShareWindowClose` if it helps in your use cases.

**Comment by s-a** [comment]
Did anyone successfuly implemented this feature?

**Comment by Gricardov** [comment]
I need this feature
