### ISSUE TITLE
Share info not appearing in Facebook iFrame

### ISSUE THREAD

**Issue by Ganasist** [nygardk/react-share#92]
It appears that the supplementary info is not showing up in our Facebook iFrames:

We pass info in like so (and this has always worked in the past):
```
<FacebookShareButton
                        className={styles.shareButton}
                        description={productDescription}
                        picture={productImage}
                        title={productBrand}
                        url={productURL}
                    >
```

The url we get back (both in iFrame and full page) contains all of these params (title, description etc). However none of that info shows up in the view... no image, no title, no description

Is it possible Facebook changed their sharer.php API?

**Comment by nygardk** [comment]
Please see #89. I will merge and publish it this week.

**Comment by Ganasist** [comment]
Thanks a million!

**Comment by Dave-Algorism** [comment]
I still have this issue. How do I solve it? Any pointers?

**Comment by nygardk** [comment]
See version `0.15.1`.
