### ISSUE TITLE
Title and picture doesn`t work

### ISSUE THREAD

**Issue by jthink0228** [nygardk/react-share#93]
here is my code in return():
            <FacebookShareButton
              url={'https://test.com.tw/Blogs/'+ this.state.id}
              title={this.state.blogName}
              picture={this.state.listPhoto}
              className="Demo__some-network__share-button">
              <FacebookIcon
                size={26}
                round />
           </FacebookShareButton>

both title and picture doesn`t work when i push share button.

the console:

FacebookShareButton warning: picture is a deprecated prop.   share-button.js:204
FacebookShareButton warning: title is a deprecated prop. Use "quote" instead. share-button.js:208

**Comment by rwojnarowski** [comment]
Just read the warning. This custom fields like title, picture and image are no longer supported by facebook sharer, use 'quote' instead.
https://developers.facebook.com/docs/apps/changelog#v2_9_deprecations

**Comment by jthink0228** [comment]
thank you
