### ISSUE TITLE
Documentation of props for specific networks is inaccurate

### ISSUE THREAD

**Issue by tomprogers** [nygardk/react-share#97]
The documentation says that, e.g. Facebook supports `title`, `description`, and `pictures`. However, this module actually supports `url`, `quote`, and `hashtag` (https://github.com/nygardk/react-share/blob/master/src/social-media-share-links.jsx#L43)

I tested Facebook, Twitter, and LinkedIn. I had to dig through your source to find the correct prop names for most of them.

**Comment by nygardk** [comment]
Now fixed!
