### ISSUE TITLE
Add Line App support please

### ISSUE THREAD

**Issue by strong0588** [nygardk/react-share#99]
would be nice  to have it since the project country that i am working mainly use Line App instead of Whatsapp. Thanks!

**Comment by facuch19** [comment]
Line app instead of ws? jaja its not a good idea.

**Comment by LorisTujiba** [comment]
yeah Line, the other packages doesn't support with SSR

**Comment by Luis-Chen** [comment]
+1  in Asia area like Japan , Taiwan  ....etc  Line app is hot ,everyone almost use

**Comment by nygardk** [comment]
Line support added in `v2.4.0`
